# Site settings
title: Tah
email: help@tah.io
description: > # this means to ignore newlines until "baseurl:"
  Control anything around you with a smartphone. Tah is an Arduino at its heart with bluetooth low energy (BLE) onboard.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://tah.io" # the base hostname & protocol for your site
twitter_username: tah_io
github_username:  tah-io

# Build settings
markdown: kramdown
