# Site wide configuration

title: Tah
locale: en_US
description: > # this means to ignore newlines until "baseurl:"
  Control anything around you with a smartphone. Tah is an Arduino at its heart with bluetooth low energy (BLE) onboard.
logo: site-logo.png
search: true
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Revealing Hour Creations
  email: help@tah.io
  disqus-shortname:
  twitter: tah_io
  facebook: pages/Tah/633568926721880
  github: tah-io
  linkedin: #username
  instagram: tah_io
  tumblr: #username
  google:
    plus: TahIoble/posts
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify: